language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t ahmadawada/docker-react -f dockerfile.dev .
script:
    - docker run -e CI=true ahmadawada/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "put the name of s3 baucket"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY